### ISSUE TITLE
[Cross Trade - Contract Bugs]: Remove unnecessary hash comparison statement from L1CrossTrade contract

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-bridge#206]
### What happened?

Comparing the l2HashValue generated within the contract and the _hash parameter in the provideCT / editFee / cancel methods is meaningless. The _hash parameter and the require statement that compares the two hash values ​​should be removed.

**Comment by zzooppii** [comment]
This is a value that checks in the front whether the input values ​​are entered correctly. 
Since there are many variables and mistakes can be made, this is a require statement that was inserted to reduce user financial losses by preventing the tx from passing if it is different from the hash value.

**Comment by blackcow1987** [comment]
@zzooppii I expect that the values ​​passed to methods such as provideCT are the values ​​parsed from the events read by the indexer. If this is true, then all values ​​including hash have the same source, so I don't understand why we double-check this again. I can't understand adding code just because it's a little bit insecure.

**Comment by zzooppii** [comment]
Yes, you understood correctly.
I added this because I wanted to make transactions more secure since if the data is tangled and a value different from the hash value is entered, it will pass through L1 but not through L2.
We will discuss whether it would be better to remove this part as a team or leave it as it is.

Thank you for your advice.

**Comment by zzooppii** [comment]
@blackcow1987 
We had a meeting about the issue.

I think it would be good if the require statement was added to provide a more stable service.
I added the require statement so that if an error occurs, it can be easily found in the frontend.
I added a commnet about the content.
https://github.com/tokamak-network/crossTrade/commit/f262cca5d8ff620535d686b5f7e9d37733776214

Thank you.
